//! Attach browser controls to the HTML generated by Topcoat.
use std::{cell::RefCell, rc::Rc};

use wasm_bindgen::prelude::*;
use wasm_bindgen_futures::spawn_local;
use web_sys::{HidDeviceFilter, HidDeviceRequestOptions, HtmlButtonElement, HtmlElement};

use crate::{
    reader::{PAXTON_VID, State, Tone, hid, reason, run},
    token::Read,
};

pub(crate) fn element(id: &str) -> HtmlElement {
    web_sys::window()
        .unwrap()
        .document()
        .unwrap()
        .get_element_by_id(id)
        .expect("element in the Topcoat page")
        .unchecked_into()
}

pub(crate) fn render(state: &State) {
    element("status")
        .set_attribute("data-tone", state.status.0.name())
        .unwrap();
    element("message").set_text_content(Some(&state.status.1));
    let card = state.card.as_ref();
    let beta = card.is_some_and(|t| t.read == Read::Hitag2);
    element("reading").set_class_name(if card.is_some() {
        "reading"
    } else {
        "reading empty"
    });
    element("number").set_text_content(Some(
        &card.map_or("--------".into(), |t| t.number.to_string()),
    ));
    element("prompt").set_hidden(card.is_some());
    element("kind").set_hidden(card.is_none());
    element("kind").set_class_name(if beta { "chip beta" } else { "chip" });
    element("kind").set_text_content(Some(if beta { "Hitag2 · beta" } else { "Mifare" }));
    element("hex").set_hidden(card.is_none());
    element("hex").set_text_content(card.map(|t| t.hex.as_str()));
    element("beta").set_class_name(if beta { "beta-note shown" } else { "beta-note" });
    for (id, text) in [
        ("copy-number", card.map(|t| t.number.to_string())),
        ("copy-hex", card.map(|t| t.hex.clone())),
    ] {
        let button: HtmlButtonElement = element(id).unchecked_into();
        button.set_disabled(card.is_none());
        button
            .set_attribute(
                "data-copied",
                if text.as_ref() == Some(&state.copied) {
                    "true"
                } else {
                    "false"
                },
            )
            .unwrap();
    }
    crate::batch_client::render(state);
    crate::net2_client::render(state);
    crate::portrait_client::render(state);
}

pub(crate) fn on_click(id: &str, f: impl FnMut() + 'static) {
    let callback = Closure::<dyn FnMut()>::new(f);
    element(id).set_onclick(Some(callback.as_ref().unchecked_ref()));
    // These controls live for the lifetime of the page.
    callback.forget();
}

#[cfg_attr(not(test), wasm_bindgen(start))]
#[cfg_attr(test, wasm_bindgen)]
pub fn start() {
    std::panic::set_hook(Box::new(|info| crashed(&info.to_string())));
    let state = Rc::new(RefCell::new(State {
        on_change: render,
        ..State::default()
    }));
    crate::net2_client::setup(state.clone());
    crate::portrait_client::setup(state.clone());
    crate::batch_client::setup(state.clone());
    render(&state.borrow());
    on_click("theme", toggle_theme);
    for (id, number) in [("copy-number", true), ("copy-hex", false)] {
        let state = state.clone();
        on_click(id, move || {
            let text = state.borrow().card.as_ref().map(|t| {
                if number {
                    t.number.to_string()
                } else {
                    t.hex.clone()
                }
            });
            let Some(text) = text else { return };
            let state = state.clone();
            spawn_local(async move {
                let clipboard = web_sys::window().unwrap().navigator().clipboard();
                if clipboard.write_text(&text).await.is_ok() {
                    let mut state = state.borrow_mut();
                    state.copied = text;
                    render(&state);
                }
            });
        });
    }

    let has_hid = js_sys::Reflect::has(&web_sys::window().unwrap().navigator(), &"hid".into())
        .unwrap_or(false);
    if !has_hid {
        state.borrow_mut().say(
            Tone::Problem,
            "WebHID is not available - open this page in Chrome or Edge",
        );
        return;
    }
    element("connect")
        .unchecked_into::<HtmlButtonElement>()
        .set_disabled(false);
    let connect_state = state.clone();
    on_click("connect", move || {
        let state = connect_state.clone();
        if state.borrow().link.dev.as_ref().is_some_and(|d| d.opened()) {
            state
                .borrow_mut()
                .say(Tone::Ready, "Already connected - present a token");
            return;
        }
        let filter = HidDeviceFilter::new();
        filter.set_vendor_id(PAXTON_VID);
        let opts = HidDeviceRequestOptions::new(&[filter]);
        // Request permission while still handling the user's click.
        let request = hid().request_device(&opts);
        spawn_local(async move {
            match request.await {
                Ok(devices) => match devices.get_checked(0) {
                    Some(dev) => run(dev, state).await,
                    None => state.borrow_mut().say(Tone::Idle, "No reader selected"),
                },
                Err(e) => state.borrow_mut().say(
                    Tone::Problem,
                    format!("Could not reach the reader: {}", reason(&e)),
                ),
            }
        });
    });
    // Reuse permission on reload; unplugging this reader still needs the picker.
    spawn_local(async move {
        if let Ok(devices) = hid().get_devices().await
            && let Some(dev) = devices
                .iter()
                .find(|d| u32::from(d.vendor_id()) == PAXTON_VID)
        {
            run(dev, state).await;
        }
    });
}

/// A panic stops the wasm for good and, left alone, the page just freezes.
/// Say so where the operator is looking. This must not panic itself, so no
/// `element`, and nothing that borrows `State`, which may be mid-borrow.
pub(crate) fn crashed(details: &str) {
    web_sys::console::error_1(&details.into());
    let Some(document) = web_sys::window().and_then(|w| w.document()) else {
        return;
    };
    // The Portraits tab hides the status line.
    if let Some(panel) = document.get_element_by_id("reader-panel") {
        let _ = panel.remove_attribute("hidden");
    }
    if let Some(status) = document.get_element_by_id("status") {
        let _ = status.set_attribute("data-tone", Tone::Problem.name());
    }
    if let Some(message) = document.get_element_by_id("message") {
        message.set_text_content(Some(&format!(
            "Tusk hit a bug and stopped. Reload the page to carry on. ({details})"
        )));
    }
}

fn toggle_theme() {
    let window = web_sys::window().unwrap();
    let Some(root) = window.document().and_then(|d| d.document_element()) else {
        return;
    };
    let dark = match root.get_attribute("data-theme") {
        Some(theme) => theme == "dark",
        None => window
            .match_media("(prefers-color-scheme: dark)")
            .ok()
            .flatten()
            .is_some_and(|m| m.matches()),
    };
    let next = if dark { "light" } else { "dark" };
    let _ = root.set_attribute("data-theme", next);
    if let Ok(Some(storage)) = window.local_storage() {
        let _ = storage.set_item("theme", next);
    }
}

#[cfg(all(test, target_arch = "wasm32"))]
mod tests {
    use wasm_bindgen_test::*;

    #[wasm_bindgen_test]
    fn a_crash_is_shown_even_on_the_portraits_tab() {
        // Inside a div of its own: the test runner reports through the body.
        let document = web_sys::window().unwrap().document().unwrap();
        let page = document.create_element("div").unwrap();
        page.set_inner_html(
            r#"<section id="reader-panel" hidden=""><p id="status" data-tone="ready"><span id="message">Ready</span></p></section>"#,
        );
        document.body().unwrap().append_child(&page).unwrap();
        super::crashed("boom");
        let html = page.inner_html();
        page.remove();
        assert!(!html.contains("hidden"), "{html}");
        assert!(html.contains(r#"data-tone="problem""#), "{html}");
        assert!(html.contains("stopped") && html.contains("boom"), "{html}");
    }
}
